# Generated by Django 4.1 on 2024-06-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Variable', models.TextField(max_length=5000)),
                ('Question_head', models.TextField(max_length=5000)),
                ('Entity_context', models.TextField(max_length=5000)),
                ('Output_format', models.TextField(max_length=5000)),
                ('Gpt_Instruction', models.TextField(max_length=5000)),
                ('Prompt1', models.TextField(max_length=5000)),
                ('Prompt2', models.TextField(max_length=5000)),
                ('Final_prompt', models.TextField(max_length=5000)),
            ],
        ),
    ]
