# Generated by Django 4.1 on 2024-06-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0002_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='Document_type',
            field=models.TextField(default='none', max_length=5000),
        ),
    ]
