# Generated by Django 4.1 on 2024-06-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0003_prompts_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompts',
            old_name='Gpt_Instruction',
            new_name='Gpt_instruction',
        ),
    ]
