# Generated by Django 4.1 on 2024-06-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Claim', '0004_rename_gpt_instruction_prompts_gpt_instruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompts',
            name='Prompt1',
        ),
        migrations.RemoveField(
            model_name='prompts',
            name='Prompt2',
        ),
    ]
